### ISSUE TITLE
Error when opening a tiff file

### ISSUE THREAD

**Issue by RandallFlagg** [OpenImageViewer/OpenImageViewer#16]
When trying to open a tif file the following error occured:
![image](https://user-images.githubusercontent.com/434681/53948595-da382a80-40d0-11e9-9c14-7bad7c625d43.png)

**Comment by TheNicker** [comment]
It seems like the code for decoding your specific file is not implemented as TIFF contains many image formats and not all are implemented.

Please upload the file causing the error.

**Comment by TheNicker** [comment]
No response for more than 12 months.
Tiff integer compatibility has been improved. 16 bit signed integer already supported and probably the rest of the formats will be supported soon.
