### ISSUE TITLE
Source is incomplete / cannot build

### ISSUE THREAD

**Issue by fire-eggs** [OpenImageViewer/OpenImageViewer#56]
- Source assumes the existence of LLUtils, which is not included.
- `oivlib\oiv\Source\ImageUtil.h` can't find Image.h, or ExoticNumbers\*.h*
- CMake files assume that easyexif, FreeTypeWrapper, and ImageCode folders are all populated. I had to edit `oivlib\oiv\CMakeLists.txt` heavily to get CMake to be happy.

**Comment by TheNicker** [comment]
Hi, 
The libraries you've mentioned are git sub modules.

The corresponding folders should be created when updating the sub modules recursively after the initial git clone.

The build process is constantly verified for each commit via the CI script.

If after properly updating the submodules the build process isn't smooth, please notify so the CI script / source code could be fixed.
