### ISSUE TITLE
Add an error message when a file can't be displayed

### ISSUE THREAD

**Issue by RandallFlagg** [OpenImageViewer/OpenImageViewer#57]
When trying to open an unsupported file nothing happens.

**Steps to reproduce:**
1. Open  an unsupported file(e.g. JSON file) from "file explorer" in Windows using "Open With"

**Expected Behavior:**
An error message is shown

**Actual Behavior:**
Nothing happens

**Comment by TheNicker** [comment]
Fixed in 5190a19
