### ISSUE TITLE
First page is shown upside down

### ISSUE THREAD

**Issue by RandallFlagg** [OpenImageViewer/OpenImageViewer#78]
Open the file attached. It shows upside down.
https://www.leadtools.com/support/forum/resource.ashx?a=544&b=1

The attached TIFF file contains 6 pages, each of which is 24 bits per pixel encoded using LZW compression.

**Comment by TheNicker** [comment]
Hi, the attached link is broken.
Please reattach  directly to this thread.
Thanks you.

**Comment by RandallFlagg** [comment]
The file was taken from the following link:
https://www.leadtools.com/support/forum/posts/t10960-
