### ISSUE TITLE
Unsupported TIFF file

### ISSUE THREAD

**Issue by RandallFlagg** [OpenImageViewer/OpenImageViewer#79]
The file attached shows as not supported:
https://www.leadtools.com/support/forum/resource.ashx?a=545&b=1

The attached TIFF file contains 11 pages, each of which is encoded differently from all the other pages. The pages are, in order:
1- Uncompressed RGB
2- Uncompressed CMYK
3- JPEG 2000 compression
4- JPEG 4:1:1 compression
5- JBIG compression
6- RLE Packbits compression
7- CMYK with RLE Packbits compression
8- YCC with RLE Packbits compression
9- LZW compression
10- CCITT Group 4 compression
11- CCITT Group 3 2-D compression

**Comment by TheNicker** [comment]
Hi, the attached link is broken.
Please reattach directly to this thread.
Thanks you.

**Comment by RandallFlagg** [comment]
The file was taken from the following link:
https://www.leadtools.com/support/forum/posts/t10960-
